In [2]:
import numpy as np
import pandas as pd
from sklearn.linear_model import LinearRegression
from sklearn.utils import shuffle

data = pd.read_csv("student-mat.csv")
data.head()

school sex  age address famsize Pstatus  Medu  Fedu     Mjob      Fjob  ...  \
0     GP   F   18       U     GT3       A     4     4  at_home   teacher  ...   
1     GP   F   17       U     GT3       T     1     1  at_home     other  ...   
2     GP   F   15       U     LE3       T     1     1  at_home     other  ...   
3     GP   F   15       U     GT3       T     4     2   health  services  ...   
4     GP   F   16       U     GT3       T     3     3    other     other  ...   

  famrel freetime  goout  Dalc  Walc health absences  G1  G2  G3  
0      4        3      4     1     1      3        6   5   6   6  
1      5        3      3     1     1      3        4   5   5   6  
2      4        3      2     2     3      3       10   7   8  10  
3      3        2      2     1     1      5        2  15  14  15  
4      4        3      2     1     2      5        4   6  10  10  

[5 rows x 33 columns]

In [3]:
data = data[["G1", "G2", "G3", "studytime", "failures", "absences"]]
predict = "G3"
x = np.array(data.drop([predict], 1))
y = np.array(data[predict])

from sklearn.model_selection import train_test_split
xtrain, xtest, ytrain, ytest = train_test_split(x, y, test_size=0.2)

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:3: FutureWarning: In a future version of pandas all arguments of DataFrame.drop except for the argument 'labels' will be keyword-only
  This is separate from the ipykernel package so we can avoid doing imports until


In [4]:
linear_regression = LinearRegression()
linear_regression.fit(xtrain, ytrain)
accuracy = linear_regression.score(xtest, ytest)
print(accuracy)

0.850052823387042


In [5]:
predictions = linear_regression.predict(xtest)
for i in range(len(predictions)):
    print(predictions[x], xtest[x], [ytest[x]])

[[ 7.55837776 15.01075067 19.03519113 13.53315911 15.01075067]
 [ 7.55837776  7.55837776 19.03519113 13.53315911 15.70631617]
 [ 5.99991707 16.99494304 19.03519113 16.90865871 12.16635601]
 ...
 [12.16635601 16.99494304 18.41374781 16.90865871 16.90865871]
 [10.93607372 13.39981157 18.41374781 13.53315911 13.53315911]
 [16.99494304  8.62956912 18.41374781 13.53315911  7.55837776]] [[[ 7  9  2  2  6]
  [16 15  3  0  0]
  [17 18  2  0 21]
  [12 14  3  0  1]
  [16 15  3  0  0]]

 [[ 7  9  2  2  6]
  [ 7  9  2  2  6]
  [17 18  2  0 21]
  [12 14  3  0  1]
  [17 15  1  0  4]]

 [[ 7  6  2  0 26]
  [16 17  3  0  0]
  [17 18  2  0 21]
  [17 17  4  0  0]
  [12 12  2  0 13]]

 ...

 [[12 12  2  0 13]
  [16 17  3  0  0]
  [18 18  3  0  5]
  [17 17  4  0  0]
  [17 17  4  0  0]]

 [[13 11  2  0  2]
  [14 13  1  0  6]
  [18 18  3  0  5]
  [12 14  3  0  1]
  [12 14  3  0  1]]

 [[16 17  3  0  0]
  [10  9  2  0  4]
  [18 18  3  0  5]
  [12 14  3  0  1]
  [ 7  9  2  2  6]]] [array([[ 8, 15, 18, 15, 15]